### PR TITLE
Some hard coded strings added to strings.xml and german translation added

### PR DESCRIPTION
**Pull request by DerSaxxe**

### CODE REVIEW

**Comment by DerSaxxe** [comment]
Sorry while you did some changes in the german strings.xml I also did many changes. Therefore you have to resolve the conflict manually.

**Review by KumarManas04 — CHANGES_REQUESTED** [review]
Since there would be more language translation contributors, let's not put the names of the translators in the same option as that of the developer. So, please change the developer section back to as it was and don't worry you will be given proper credits within the app. I am thinking of a different option for translation credits.

**Comment by DerSaxxe** [comment]
Okay I removed the german translator ;-)
Additional I changed the support_development_dialog to a scrollable dialog because it was too small for smaller screens and in landscape orientation.

**Comment by DerSaxxe** [comment]
With the latest commit nearly all strings were moved to strings.xml and they are translated to german. Therefore I will stop my activities until you send a message if you need any updates.
I think now you should update the translation files at OneSky. Also you can add the Play Store string at OneSky

**Review by KumarManas04 — APPROVED** [review]
Awesome work! Thanks for your time.

**Comment by KumarManas04** [comment]
> I think now you should update the translation files at OneSky. Also you can add the Play Store string at OneSky

Updated the translations at OneSky

**Comment by KumarManas04** [comment]
> Okay I removed the german translator ;-)
> Additional I changed the support_development_dialog to a scrollable dialog because it was too small for smaller screens and in landscape orientation.

I have added a new contributions dialog in the AboutFragment and added your name to it. Thanks for the help.

**Pull request merged**
