### PR TITLE
German translation, about version bugfix, html in changelog alert

### PR DESCRIPTION
**Pull request by DerSaxxe**
Also many hard coded strings moved to strings.xml
Please update translation project at OneSky
Thank you

### CODE REVIEW

**Review by KumarManas04 — CHANGES_REQUESTED** [review]
Some fixes are required - 
1. 'write_something' in the strings.xml is neither linked to the UI nor added to the english translation.
2. 'other' in the strings.xml is neither linked to the UI nor added to the english translation.
3. Translation of 'amoled' in german should be 'Amoled' and not 'Dark Mode' as it is a screen type
4. Remove quotes from 'encrypted_sync_summary' translation in german strings.xml
Kindly make these changes. Everything else is fine.

**Comment by DerSaxxe** [comment]
> 1. 'write_something' in the strings.xml is neither linked to the UI nor added to the english translation.

This is not correct. Please look at fragment_note_edit.xml
> 2. 'other' in the strings.xml is neither linked to the UI nor added to the english translation.

This is not correct. Please look at fragment_settings.xml
> 3. Translation of 'amoled' in german should be 'Amoled' and not 'Dark Mode' as it is a screen type

I think AMOLED is not the best choice because you can also set this theme on devices with other screen types than AMOLED. In german language "Dark Mode" should be better because most people knows what that means - deep black background. Why not?
> 4. Remove quotes from 'encrypted_sync_summary' translation in german strings.xml

Done ;-)

**Comment by KumarManas04** [comment]
Apologies for requests 1 and 2. I must have missed checking these.

> I think AMOLED is not the best choice because you can also set this theme on devices with other screen types than AMOLED. In german language "Dark Mode" should be better because most people knows what that means - deep black background. Why not?

There is already a dark mode for normal screens but the Amoled mode is designed to increase battery efficiency on AMOLED screens since in that mode the screen is black at most parts. So users must know this. Hence, the name should be 'Amoled' only and not 'Dark Mode'.

**Comment by DerSaxxe** [comment]
What about "Black" since most common german people don't know what AMOLED means?

**Review by KumarManas04 — CHANGES_REQUESTED** [review]
Please make the following changes:
1. The 'reminder_set' string should contain '\n' character. It was intentional.

(Optional)
2. Kindly remove 'auto_sync' and 'auto_sync_pref_summary' strings as they are no longer required.

And if you think making the 'amoled' string 'Black' in german is fine, then go for it.

**Comment by DerSaxxe** [comment]
> 1. The 'reminder_set' string should contain '\n' character. It was intentional.

Sorry this was not my mistake, seems to be a bug in the translation tool in android studio. I fixed it.
> 2. Kindly remove 'auto_sync' and 'auto_sync_pref_summary' strings as they are no longer required.

I did it.

**Comment by KumarManas04** [comment]
Great work @SIRSteiner 
Thanks for your time

**Pull request merged**
